name: Build and Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # 수동으로 워크플로우를 실행할 수 있게 함

jobs:
  build-and-publish:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest
    
    # OIDC 토큰 인증을 위한 권한 추가
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 